source "http://localhost:65535/"
# Did not want to link the berks file to outside link https://supermarket.chef.io so I set it to listen
# to random unused port.
metadata

cookbook "kitchen-test-helper", "~> 2.0.0", github: "kbvincent/kitchen-test-helper/", branch: "master"