<%
  `cat #{ENV['INDUCTOR_WORKORDER_PATH']}|python -c 'import sys,json; print json.load(sys.stdin)["workorder"]["payLoad"]["SecuredBy"][0]["ciAttributes"]["private"]' > /tmp/key`
  computeip = `cat #{ENV['INDUCTOR_WORKORDER_PATH']}|python -c 'import sys,json; print json.load(sys.stdin)["workorder"]["payLoad"]["ManagedVia"][0]["ciAttributes"]["private_ip"]'`
%>
driver:
  name: proxy
  host: <%= computeip %>
  reset_command: "exit 0"
  port: 22
  username: oneops
  ssh_key: /tmp/key
  ftp_proxy: <%= ENV['CLIENT_WORKORDER_PATH'] %>
provisioner:
  require_chef_omnibus: false
  chef_solo_path: /usr/local/bin/chef-solo
  script: "bootstrap.sh"
platforms:
  - name: centos-7.2
suites:
  - name: add
    run_list:
#      - recipe[kitchen-test-helper]
#      - recipe[user::add]
    attributes:
  - name: delete
    run_list:
#      - recipe[kitchen-test-helper]
#      - recipe[User::add]
#      - recipe[User::delete]
    attributes:
      user:
        username: 'app'
        login_shell: '/bin/bash'
        group: '["app"]'
